// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import {Test} from "forge-std/Test.sol";
import {SimpleStorage} from "../src/SimpleStorage.sol";

/// @title SimpleStorageTest
/// @notice Tests for the SimpleStorage contract
/// @dev Example of how to structure tests in Foundry
contract SimpleStorageTest is Test {
    // ==========================================================================
    // VARIABLES
    // ==========================================================================

    SimpleStorage public simpleStorage;

    // Test addresses
    address public alice = makeAddr("alice");
    address public bob = makeAddr("bob");

    // ==========================================================================
    // SETUP
    // ==========================================================================

    /// @notice Runs before EACH test
    function setUp() public {
        // Deploy a fresh contract for each test
        simpleStorage = new SimpleStorage();
    }

    // ==========================================================================
    // BASIC TESTS
    // ==========================================================================

    /// @notice Initial value should be 0
    function test_InitialValueIsZero() public view {
        assertEq(simpleStorage.favoriteNumber(), 0);
    }

    /// @notice store() should save the number correctly
    function test_StoreNumber() public {
        simpleStorage.store(42);
        assertEq(simpleStorage.favoriteNumber(), 42);
    }

    /// @notice retrieve() should return the same value as favoriteNumber
    function test_RetrieveMatchesFavoriteNumber() public {
        simpleStorage.store(123);
        assertEq(simpleStorage.retrieve(), simpleStorage.favoriteNumber());
    }

    /// @notice increment() should add 1 to the number
    function test_Increment() public {
        simpleStorage.store(10);
        simpleStorage.increment();
        assertEq(simpleStorage.favoriteNumber(), 11);
    }

    /// @notice decrement() should subtract 1 from the number
    function test_Decrement() public {
        simpleStorage.store(10);
        simpleStorage.decrement();
        assertEq(simpleStorage.favoriteNumber(), 9);
    }

    // ==========================================================================
    // EVENT TESTS
    // ==========================================================================

    /// @notice store() should emit NumberUpdated with correct values
    function test_StoreEmitsEvent() public {
        // Configure expected event
        vm.expectEmit(true, true, true, true);
        // Declare expected event (from 0 to 42, by this contract)
        emit SimpleStorage.NumberUpdated(0, 42, address(this));

        // Execute the function
        simpleStorage.store(42);
    }

    /// @notice increment() should emit NumberUpdated
    function test_IncrementEmitsEvent() public {
        simpleStorage.store(5);

        vm.expectEmit(true, true, true, true);
        emit SimpleStorage.NumberUpdated(5, 6, address(this));

        simpleStorage.increment();
    }

    /// @notice decrement() should emit NumberUpdated
    function test_DecrementEmitsEvent() public {
        simpleStorage.store(5);

        vm.expectEmit(true, true, true, true);
        emit SimpleStorage.NumberUpdated(5, 4, address(this));

        simpleStorage.decrement();

        simpleStorage.increment();
    }

    // ==========================================================================
    // TESTS WITH DIFFERENT USERS
    // ==========================================================================

    /// @notice Anyone can store a number
    function test_AnyoneCanStore() public {
        // Alice stores a number
        vm.prank(alice);
        simpleStorage.store(100);
        assertEq(simpleStorage.favoriteNumber(), 100);

        // Bob overwrites it
        vm.prank(bob);
        simpleStorage.store(200);
        assertEq(simpleStorage.favoriteNumber(), 200);
    }

    /// @notice Event should record who made the change
    function test_EventRecordsCorrectCaller() public {
        vm.expectEmit(true, true, true, true);
        emit SimpleStorage.NumberUpdated(0, 999, alice);

        vm.prank(alice);
        simpleStorage.store(999);
    }

    // ==========================================================================
    // FUZZ TESTS
    // ==========================================================================

    /// @notice store() should work with any valid number
    /// @param _number A random number generated by the fuzzer
    function testFuzz_Store(uint256 _number) public {
        simpleStorage.store(_number);
        assertEq(simpleStorage.favoriteNumber(), _number);
    }

    /// @notice increment() should not overflow
    function testFuzz_IncrementNoOverflow(uint256 _initial) public {
        // Only test values that won't overflow
        vm.assume(_initial < type(uint256).max);

        simpleStorage.store(_initial);
        simpleStorage.increment();
        assertEq(simpleStorage.favoriteNumber(), _initial + 1);
    }

    /// @notice decrement() should not underflow
    function testFuzz_DecrementNoUnderflow(uint256 _initial) public {
        // Only test values that won't underflow
        vm.assume(_initial > 0);

        simpleStorage.store(_initial);
        simpleStorage.decrement();
        assertEq(simpleStorage.favoriteNumber(), _initial - 1);
    }
}
